<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsNotAsErrors>IDE0055,IDE0100</WarningsNotAsErrors>
    <NoWarn>CA1515</NoWarn>
    <AnalysisLevel>latest-all</AnalysisLevel>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../common/common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CsCheck" Version="4.6.2" />
    <PackageReference Include="TUnit" Version="1.28.7" />
  </ItemGroup>
</Project>