<Project Sdk="Microsoft.NET.Sdk">

<PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsNotAsErrors>IDE0055</WarningsNotAsErrors>
    <AnalysisLevel>latest-all</AnalysisLevel>
    <LangVersion>preview</LangVersion>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

</Project>
